info:
  contact: {}
  description: 锦鲤管理面板主打安全、可靠、性能调优。容器化管理
  license:
    name: GNU v3
    url: https://github.com/jinlicode/jinli-panel/blob/master/LICENSE
  termsOfService: https://github.com/jinlicode/jinli-panel
  title: 锦鲤管理面板
  version: "2.0"
paths: {}
swagger: "2.0"
