name: Aliyun Build Image

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Node intsll
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd vue-admin && yarn
      - run: cd vue-admin && yarn build

      - name: Go build
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.15
      - run: go build
      
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_ALIYUN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_ALIYUN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin registry.cn-beijing.aliyuncs.com
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build \
          --platform=linux/amd64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag registry.cn-beijing.aliyuncs.com/jinlicode/jinli-panel:latest
