name: Project Build master

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Node intsll
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd vue-admin && yarn
      - run: cd vue-admin && yarn build

      - name: Go build
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go get github.com/rakyll/statik
      - run: ~/go/bin/statik -src=./html/
      - run: GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"'

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: jinli-panel
          args: -fq9 --brute
      
      - name: upload test build
        uses: actions/upload-artifact@v2
        with:
          name: jinli-panel
          path: jinli-panel
          retention-days: 90

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'jinli-panel'
          remote_path: '/var/jinli/code/release_jinli_plus/pre'
